---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kinoite-wm-nvidia
# description will be included in the image's metadata
description: Personal OS Kinoite image with Nira and Hyprland WM.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - from-file: general.yml
  - from-file: fonts.yml
  - from-file: virtualization.yml
  - from-file: general-wm.yml
  - from-file: swaync.yml
  - from-file: niri.yml
  - from-file: hyprland.yml
  - from-file: kde.yml
  - from-file: flatpak.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

